# Introducción a paquetes en Python. El paquete *numpy*

En esta sección introducimos el uso de paquetes (también llamados módulos) en Python a través del módulo *numpy*.

El módulo *numpy* es el estándar para cálculo numérico en Python. Es un paquete que provee a Python de estructuras de datos a las que denomiamos *arrays*, que se utilizan para objetos de tipo vectorial y matricial (o de rango mayor). Está implementado en C y Fortran de modo que, cuando los cálculos son vectorizados (formulados con vectores y matrices), el rendimiento es excelnte.

## 1. Importando todo el contenido de numpy

Para usar numpy necesitamos **importar el módulo**. La forma más sencilla consiste en **cargar todo su contenido** (excepto los nombres que empiecen por "_") dentro del espacio de nombres actual (el conjunto de variables, nombres de funciones, etc). Para ello, usamos la notación `import *`, que significa, "importar todo el contenido".

In [3]:
from numpy import *

De esta forma, tendremos acceso directo a *arrays* de matrices y vectores:

In [8]:
# Un vector: el argumento de la función array es una lista de Python
v = array([1,2,3,4])
# ¿Qué es v?
v

array([1, 2, 3, 4])

In [11]:
# Una matriz: el argumento de la función array es una lista anidada de Python
A = array([[1, 2], [3, 4]])
# ¿Qué es A?
A

array([[1, 2],
       [3, 4]])

Ambos objetos, *v* y *A*, **son del mismo tipo**: del tipo *ndarray* (*array* de *n*úmeros en *d*oble precisión), provisto por el módulo *numpy*:

In [20]:
# La función "type" devuelve el tipo de dato al que pertenece una variable
print("Tipo de v:", type(v))
print("Tipo de A:", type(A))

Tipo de v: <class 'numpy.ndarray'>
Tipo de A: <class 'numpy.ndarray'>


Sólo se diferencian en su forma:

In [21]:
# La función "shape" devuelve la forma (tamaño en cada dirección)
print("Forma de v:", shape(v))
print("Forma de A:", shape(A))

Forma de v: (4,)
Forma de A: (2, 2)


Tanto *v* como *A* almacenan en memoria 4 números reales, así que tienen el mismo tamaño:

In [27]:
print("Tamaño de v:", size(v))
print("Tamaño de A:", size(A))

Tamaño de v: 4
Tamaño de A: 4


#### ¿Por qué *arrays* sí y listas no?
Por ahora, los datos de tipo *numpy.ndarray* parecen ser simplemente listas anidadas.  Entonces, ¿por qué 
no usar simplemente listas para hacer cálculos, en lugar de crear un tipo nuevo de *array* ?

Existen varias razones:

- Las listas Python son muy generales (pueden contener cualquier tipo de objeto). El implementar funciones matemáticas (suma, producto, etc.) para las listas es *poco eficiente* debido la asignación dinámica que utiliza este tipo de datos.
- Pero los *arrays* de *numpy* no son listas: tienen tipo estático y homogéneo (el tipo de elementos que contienen es determinado cuando se crea el arreglo). Por este motivo:
    - Son eficientes en el uso de memoria.
    - Permiten desarrollar implementaciones rápidas de funciones matemáticas (multiplicación, suma, etc) usando lenguajes compilados (se usan C y Fortran).
    
Los siguientes ejemplos ilustran cómo es posible operar con *arrays* (pero por contra, son menos flexibles que las listas). 

In [45]:
0.5*v + v

array([ 1.5,  3. ,  4.5,  6. ])

In [80]:
cos(v) + sin(v) + log(2*v) # Las funciones provistas por numpy pueden actuar sobre arrays

array([ 2.07492047,  1.87944495,  0.94288698,  0.66899543])

In [64]:
# En una matriz, calculamos el producto ELEMENTO a ELEMENTO..
A*A

array([[ 1,  4],
       [ 9, 16]])

In [65]:
# ... o el producto matricial
dot(A,A)

array([[ 7, 10],
       [15, 22]])

In [69]:
lista =  [1,2,3,4]
lista.append(5) # OK
v.append(5) # Error los arrays tiene tamaño fijo y no se pueden añadir más elementos!

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [76]:
A[0,1] = 3.2 # OK, acceso a la primera fila y segunda columna
A[1,1] = "hola" # Error, los arrays tienen tipo de dato homogéneo, no valen cadenas de caracteres

ValueError: invalid literal for int() with base 10: 'hola'

### Inconvenientes de cargar todo el contenido de un paquete

Al principio de esta sección comenzamos importando todo el contenido de numpy en el espacio de nombres actual:

In [118]:
from numpy import *

Esto resulta muy cómodo, pues podemos usar directamente todos los nombres (funciones, variables) de este módulo. Pero el importar todo el contenido de un módulo puede tener efectos perniciosos, como se muestra a continuación:

In [120]:
size = 3405
print("Supongamos que el tamaño de una muestra es:", size, ". Perfecto")
# ...después de muchas líneas de código, queremos trabajar con numpy...
from numpy import *
# ...y después de muchas más líneas de código...
if(size != 3405):
    print("Pero... ¿qué pasa? Ahora el tamaño de la muestra es:", size, "¡¡ERROR TERRIBLE!!")
    print("¿Qué es ahora la variable 'size'?:", type(size), "...es el nombre de una función de numpy.")

Supongamos que el tamaño de una muestra es: 3405 . Perfecto
Pero... ¿qué pasa? Ahora el tamaño de la muestra es: <function size at 0x7f752ffd8950> ¡¡ERROR TERRIBLE!!
¿Qué es ahora la variable 'size'?: <class 'function'> ...es el nombre de una función de numpy.


A continuación, veremos la fórma de trabajar aconsejada en Python. Antes de ello, reinicamos python para partir de un espacio de nombres limpio.

In [122]:
%reset -f

## 2. Uso de forma explícita del paquete numpy

El cargar todo el contenido de un paquete puede originar errores, como el anteior. En general, es más aconsejable usar los paquetes de forma explícita, como se comenta a continuación.

In [123]:
import numpy as np

En este caso, hemos cargado el paquete *numpy* (con el alias *np*, que se usa habitualmente). Pero su contenido no se carga en el espacio de nombres actual y la funciones de *numpy* se pueden usar como "np.funcion" (y de forma similar las variables). Algunos ejemplos:

In [124]:
A = np.array([[1,2,3],[4,5,6]])

In [126]:
np.size(A) # Tamaño

6

In [128]:
B = np.tanh(A) # Tangente hiperbólica de los elementos de A
B

array([[ 0.76159416,  0.96402758,  0.99505475],
       [ 0.9993293 ,  0.9999092 ,  0.99998771]])

### Para saber más...
...se puede consultar por ejemplo la **lección 2 de las clases de Python científico** de J.R.Johansson, https://github.com/gfrubi/clases-python-cientifico/blob/master/Lecture-2-Numpy.ipynb (traducidas/adaptasdas por G.F. Rubilar, https://github.com/gfrubi/clases-python-cientifico/blob/master/Lecture-2-Numpy.ipynb), en las que se ha inspirado, en parte, este cuaderno